extends RefCounted
## Original effects generated by tools/build_gunshots.py.
const SAMPLES := {
	"musket": [preload("res://assets/audio/gunshots/musket_1.wav"), preload("res://assets/audio/gunshots/musket_2.wav"), preload("res://assets/audio/gunshots/musket_3.wav")],
	"shotgun": [preload("res://assets/audio/gunshots/shotgun_1.wav"), preload("res://assets/audio/gunshots/shotgun_2.wav"), preload("res://assets/audio/gunshots/shotgun_3.wav")],
	"rifle": [preload("res://assets/audio/gunshots/rifle_1.wav"), preload("res://assets/audio/gunshots/rifle_2.wav"), preload("res://assets/audio/gunshots/rifle_3.wav")],
	"pistol": [preload("res://assets/audio/gunshots/pistol_1.wav"), preload("res://assets/audio/gunshots/pistol_2.wav"), preload("res://assets/audio/gunshots/pistol_3.wav")],
	"revolver": [preload("res://assets/audio/gunshots/revolver_1.wav"), preload("res://assets/audio/gunshots/revolver_2.wav"), preload("res://assets/audio/gunshots/revolver_3.wav")],
	"pepperbox": [preload("res://assets/audio/gunshots/pepperbox_1.wav"), preload("res://assets/audio/gunshots/pepperbox_2.wav"), preload("res://assets/audio/gunshots/pepperbox_3.wav")],
	"blunderbuss": [preload("res://assets/audio/gunshots/blunderbuss_1.wav"), preload("res://assets/audio/gunshots/blunderbuss_2.wav"), preload("res://assets/audio/gunshots/blunderbuss_3.wav")],
	"heavy_rifle": [preload("res://assets/audio/gunshots/heavy_rifle_1.wav"), preload("res://assets/audio/gunshots/heavy_rifle_2.wav"), preload("res://assets/audio/gunshots/heavy_rifle_3.wav")],
}
