extends RefCounted
## Fictional gameplay balance for historical designs; stable IDs preserve old saves.
const DEFAULTS := {"bullet_speed": 300.0, "automatic": false, "move_reload": true, "projectile_speed": 0.0, "noise_radius": 55.0, "range": 100.0, "effective_range": 45.0, "minimum_damage": 0.55, "recoil": 1.0, "kick": 0.025, "aim_fov": 64.0, "switch_time": 0.8, "ammo_cost": 3, "limb_force": 1.0, "secondary": false}
const WEAPONS: Array[Dictionary] = [
	{"id":"frontier_musket", "bullet_speed":180.0, "name":"FRONTIER MUSKET", "tag":"01 / FLINTLOCK", "year":1777, "family":"longarm", "price":125, "magazine":1, "reserve":14, "damage":115.0, "pellets":1, "interval":1.0, "reload":3.25, "spread":0.007, "sound":"musket", "ammo_type":"MUSKET BALL", "recoil":1.45, "kick":0.050, "move_reload":false, "effective_range":38.0, "ammo_cost":2, "reload_stages":["POUR POWDER","LOAD BALL","RAM BALL","COCK HAMMER"], "description":"A hard-hitting flintlock. One shot.\nStand still for the long muzzle reload."},
	{"id":"coach_double", "name":"HAMMER COACH GUN", "tag":"02 / DOUBLE BARREL", "year":1878, "family":"longarm", "price":300, "magazine":2, "reserve":14, "damage":13.0, "pellets":8, "interval":0.42, "reload":6.0, "spread":0.052, "sound":"shotgun", "ammo_type":"SHOT SHELL", "recoil":1.65, "kick":0.050, "range":38.0, "effective_range":9.0, "minimum_damage":0.18, "ammo_cost":4, "reload_stages":["BREAK OPEN","EXTRACT SHELLS","LOAD TWO SHELLS","CLOSE & COCK"], "description":"Two fast, close-range shots.\nBreak open and load both barrels by hand."},
	{"id":"winchester_1873", "name":"WINCHESTER 1873", "tag":"03 / LEVER CARBINE", "year":1873, "family":"longarm", "price":650, "magazine":12, "reserve":24, "damage":58.0, "pellets":1, "interval":0.82, "reload":9.5, "spread":0.010, "sound":"rifle", "ammo_type":"RIFLE CARTRIDGE", "recoil":0.90, "kick":0.022, "reload_stages":["OPEN LOADING GATE","FEED CARTRIDGES","CLOSE GATE","CYCLE LEVER"], "description":"A twelve-shot lever carbine.\nManual cycling; a slow tube-magazine refill."},
	{"id":"hunting_crossbow", "name":"HUNTING CROSSBOW", "tag":"04 / QUIET HUNTER", "year":1650, "family":"special", "price":225, "magazine":1, "reserve":12, "damage":85.0, "pellets":1, "interval":1.0, "reload":5.5, "spread":0.003, "sound":"crossbow", "ammo_type":"BOLT", "recoil":0.35, "kick":0.009, "projectile_speed":48.0, "noise_radius":5.0, "range":85.0, "effective_range":45.0, "limb_force":0.18, "ammo_cost":3, "reload_stages":["SET SPANNING LEVER","DRAW STRING","SEAT BOLT","READY"], "description":"Quiet, visible bolts with travel time and drop.\nAim ahead. Spanning the bow takes time."},
	{"id":"dueling_flintlock", "name":"DUELING FLINTLOCK", "tag":"05 / SINGLE-SHOT PISTOL", "year":1790, "family":"sidearm", "price":75, "magazine":1, "reserve":12, "damage":76.0, "pellets":1, "interval":1.1, "reload":7.2, "spread":0.019, "sound":"pistol", "ammo_type":"PISTOL BALL", "recoil":1.15, "kick":0.045, "range":55.0, "effective_range":18.0, "ammo_cost":2, "reload_stages":["POUR POWDER","PATCH & BALL","RAM CHARGE","PRIME & COCK"], "description":"An inexpensive engraved flintlock sidearm.\nPowerful up close, painfully slow to reload."},
	{"id":"blunderbuss", "name":"BRASS BLUNDERBUSS", "tag":"06 / MUZZLE-LOADED SHOT", "year":1780, "family":"special", "price":100, "magazine":1, "reserve":10, "damage":9.0, "pellets":12, "interval":1.2, "reload":8.4, "spread":0.092, "sound":"blunderbuss", "ammo_type":"LOOSE SHOT", "recoil":1.9, "kick":0.064, "range":25.0, "effective_range":7.0, "minimum_damage":0.12, "ammo_cost":3, "reload_stages":["POUR POWDER","ADD SHOT & WAD","RAM CHARGE","PRIME LOCK"], "description":"A flared brass muzzle and a wide shot cloud.\nWait until they are close. Then reload for ages."},
	{"id":"allen_pepperbox", "name":"ALLEN PEPPERBOX", "tag":"07 / SIX ROTATING BARRELS", "year":1837, "family":"sidearm", "price":150, "magazine":6, "reserve":18, "damage":30.0, "pellets":1, "interval":0.60, "reload":14.0, "spread":0.037, "sound":"pepperbox", "ammo_type":"PISTOL BALL", "recoil":0.85, "kick":0.026, "range":35.0, "effective_range":11.0, "minimum_damage":0.3, "ammo_cost":2, "reload_stages":["CHARGE SIX BARRELS","SEAT BALLS","FIT SIX CAPS","RESET HAMMER"], "description":"Six compact barrels rotate with the trigger.\nFast emergency shots, poor reach, long reload."},
	{"id":"colt_navy_1851", "name":"COLT 1851 NAVY", "tag":"08 / CAP-AND-BALL REVOLVER", "year":1851, "family":"sidearm", "price":200, "magazine":6, "reserve":18, "damage":40.0, "pellets":1, "interval":0.55, "reload":16.0, "spread":0.016, "sound":"revolver", "ammo_type":"PISTOL BALL", "recoil":0.80, "kick":0.028, "range":65.0, "effective_range":24.0, "ammo_cost":2, "reload_stages":["HALF-COCK","CHARGE CHAMBERS","RAM SIX BALLS","FIT CAPS"], "description":"Brass furniture and an octagonal barrel.\nSix deliberate shots before a lengthy reload."},
	{"id":"remington_1858", "name":"REMINGTON 1858", "tag":"09 / SOLID-FRAME REVOLVER", "year":1858, "family":"sidearm", "price":250, "magazine":6, "reserve":18, "damage":47.0, "pellets":1, "interval":0.60, "reload":14.0, "spread":0.012, "sound":"revolver", "ammo_type":"PISTOL BALL", "recoil":0.95, "kick":0.034, "range":75.0, "effective_range":28.0, "ammo_cost":2, "reload_stages":["HALF-COCK","POWDER & BALL","RAM CHAMBERS","REPLACE CAPS"], "description":"A sturdy top strap and six heavy ball loads.\nAccurate for a sidearm; every reload is a risk."},
	{"id":"lemat_1856", "name":"LEMAT REVOLVER", "tag":"10 / NINE SHOTS + SHOT BARREL", "year":1856, "family":"sidearm", "price":325, "magazine":9, "reserve":18, "damage":42.0, "pellets":1, "interval":0.65, "reload":19.0, "spread":0.022, "sound":"revolver", "ammo_type":"PISTOL BALL", "recoil":1.0, "kick":0.035, "range":60.0, "effective_range":22.0, "ammo_cost":2, "secondary":true, "reload_stages":["CHARGE NINE CHAMBERS","RAM BALLS","CAP CYLINDER","SET HAMMER"], "description":"Nine chambers around a central shot barrel.\n[V] selects the single close-range shotgun charge."},
	{"id":"remington_derringer", "name":"REMINGTON DERRINGER", "tag":"11 / OVER-UNDER POCKET PISTOL", "year":1866, "family":"sidearm", "price":90, "magazine":2, "reserve":12, "damage":43.0, "pellets":1, "interval":0.48, "reload":4.8, "spread":0.033, "sound":"pistol", "ammo_type":"PISTOL CARTRIDGE", "recoil":1.1, "kick":0.046, "range":35.0, "effective_range":10.0, "minimum_damage":0.35, "switch_time":0.5, "reload_stages":["TIP BARRELS","EXTRACT CASES","LOAD TWO ROUNDS","LATCH & COCK"], "description":"Two stacked barrels in a tiny frame.\nA quick-drawing last resort with very short reach."},
	{"id":"colt_saa_1873", "name":"COLT SINGLE ACTION", "tag":"12 / 1873 ARMY REVOLVER", "year":1873, "family":"sidearm", "price":350, "magazine":6, "reserve":18, "damage":55.0, "pellets":1, "interval":0.50, "reload":9.0, "spread":0.014, "sound":"revolver", "ammo_type":"PISTOL CARTRIDGE", "recoil":1.15, "kick":0.042, "range":75.0, "effective_range":28.0, "reload_stages":["OPEN LOADING GATE","EJECT CASES","LOAD SIX ROUNDS","CLOSE & COCK"], "description":"A strong six-shooter with a fluted cylinder.\nEach spent case must be ejected separately."},
	{"id":"schofield_1875", "name":"SCHOFIELD REVOLVER", "tag":"13 / TOP-BREAK REVOLVER", "year":1875, "family":"sidearm", "price":400, "magazine":6, "reserve":18, "damage":52.0, "pellets":1, "interval":0.58, "reload":5.5, "spread":0.013, "sound":"revolver", "ammo_type":"PISTOL CARTRIDGE", "recoil":1.05, "kick":0.038, "range":75.0, "effective_range":30.0, "reload_stages":["UNLATCH FRAME","BREAK & EJECT","LOAD SIX ROUNDS","CLOSE FRAME"], "description":"A hinged frame ejects all six cases at once.\nQuicker recovery, but still six shots before empty."},
	{"id":"snider_enfield", "name":"SNIDER-ENFIELD", "tag":"14 / HINGED BREECH RIFLE", "year":1866, "family":"longarm", "price":375, "magazine":1, "reserve":12, "damage":135.0, "pellets":1, "interval":1.1, "reload":4.3, "spread":0.009, "sound":"heavy_rifle", "ammo_type":"HEAVY CARTRIDGE", "recoil":1.60, "kick":0.053, "effective_range":65.0, "ammo_cost":4, "reload_stages":["OPEN BREECH","EXTRACT CASE","INSERT CARTRIDGE","CLOSE & COCK"], "description":"A heavy single-shot conversion rifle.\nHard impact, hinged breech, one chance at a time."},
	{"id":"martini_henry", "name":"MARTINI-HENRY", "tag":"15 / FALLING-BLOCK RIFLE", "year":1871, "family":"longarm", "price":500, "magazine":1, "reserve":12, "damage":150.0, "pellets":1, "interval":1.0, "reload":3.8, "spread":0.006, "sound":"heavy_rifle", "ammo_type":"HEAVY CARTRIDGE", "recoil":1.75, "kick":0.060, "effective_range":80.0, "ammo_cost":4, "reload_stages":["LOWER LEVER","EJECT CASE","LOAD CARTRIDGE","RAISE LEVER"], "description":"A powerful falling-block service rifle.\nExcellent stopping power; punishing recoil."},
	{"id":"sharps_1874", "name":"SHARPS 1874", "tag":"16 / HEAVY SPORTING RIFLE", "year":1874, "family":"longarm", "price":700, "magazine":1, "reserve":10, "damage":190.0, "pellets":1, "interval":1.2, "reload":4.5, "spread":0.0025, "sound":"heavy_rifle", "ammo_type":"HEAVY CARTRIDGE", "recoil":2.0, "kick":0.070, "range":150.0, "effective_range":110.0, "aim_fov":52.0, "ammo_cost":5, "switch_time":1.1, "reload_stages":["LOWER BLOCK","REMOVE CASE","LOAD CARTRIDGE","CLOSE & COCK"], "description":"A long octagonal barrel and raised tang sight.\nDevastating precision, heavy recoil, ten spare rounds."},
	{"id":"spencer_1865", "name":"SPENCER CARBINE", "tag":"17 / SEVEN-SHOT REPEATER", "year":1865, "family":"longarm", "price":550, "magazine":7, "reserve":21, "damage":78.0, "pellets":1, "interval":0.95, "reload":7.5, "spread":0.013, "sound":"rifle", "ammo_type":"RIFLE CARTRIDGE", "recoil":1.05, "kick":0.030, "effective_range":48.0, "reload_stages":["OPEN BUTT MAGAZINE","WITHDRAW FOLLOWER","LOAD SEVEN ROUNDS","CLOSE & CYCLE"], "description":"Seven rounds feed from a tube inside the stock.\nCycle the lever and cock the hammer between shots."},
	{"id":"winchester_1887", "name":"WINCHESTER 1887", "tag":"18 / LEVER SHOTGUN", "year":1887, "family":"longarm", "price":575, "magazine":5, "reserve":15, "damage":11.0, "pellets":9, "interval":0.95, "reload":9.0, "spread":0.046, "sound":"shotgun", "ammo_type":"SHOT SHELL", "recoil":1.60, "kick":0.051, "range":42.0, "effective_range":12.0, "minimum_damage":0.2, "ammo_cost":4, "reload_stages":["OPEN LEVER","FEED SHOT SHELLS","FILL MAGAZINE","CLOSE ACTION"], "description":"Five shot shells and a large loop lever.\nGood pack control, close range, slow replenishment."},
	{"id": "throwing_knife", "name": "THROWING KNIVES", "tag": "19 / FIELDCRAFT", "year": 1700, "family": "special", "price": 35, "magazine": 3, "reserve": 0, "damage": 13, "pellets": 1, "interval": 0.22, "reload": 0.22, "spread": 0.08, "sound": "crossbow", "ammo_type": "THROWN WEAPON", "projectile_speed": 32, "noise_radius": 3.0, "range": 24, "effective_range": 12, "minimum_damage": 0.4, "recoil": 0.15, "kick": 0.008, "limb_force": 0.1, "ammo_cost": 1, "vital_bonus": 3.5, "reload_stages": ["TAKE AMMUNITION", "SET GRIP", "PREPARE", "READY"], "description": "Three ready knives, rapid throws. Quiet curved flight; precise vital hits remain essential."},
	{"id": "throwing_axe", "name": "BELT AXE", "tag": "20 / FIELDCRAFT", "year": 1700, "family": "special", "price": 45, "magazine": 1, "reserve": 8, "damage": 22, "pellets": 1, "interval": 1.1, "reload": 1.8, "spread": 0.095, "sound": "crossbow", "ammo_type": "THROWN WEAPON", "projectile_speed": 13, "noise_radius": 3.0, "range": 15, "effective_range": 6.75, "minimum_damage": 0.4, "recoil": 0.15, "kick": 0.008, "limb_force": 0.1, "ammo_cost": 1, "vital_bonus": 2.8, "reload_stages": ["TAKE AMMUNITION", "SET GRIP", "PREPARE", "READY"], "description": "Cheap, unforgiving and quiet. Curved flight; lead your target. Precise vital hits are essential."},
	{"id": "hunting_spear", "name": "HUNTING SPEAR", "tag": "21 / FIELDCRAFT", "year": 1700, "family": "special", "price": 25, "magazine": 1, "reserve": 0, "damage": 160, "pellets": 1, "interval": 0.3, "reload": 0.3, "spread": 0.065, "sound": "crossbow", "ammo_type": "THROWN WEAPON", "projectile_speed": 30, "noise_radius": 3.0, "range": 38, "effective_range": 24, "minimum_damage": 0.65, "recoil": 0.15, "kick": 0.008, "limb_force": 0.1, "ammo_cost": 6, "vital_bonus": 3.0, "reload_stages": ["TAKE AMMUNITION", "SET GRIP", "PREPARE", "READY"], "description": "One heavy spear. Fast release and devastating damage; choose your throw carefully."},
	{"id": "self_bow", "name": "ASH SELF BOW", "tag": "22 / FIELDCRAFT", "year": 1700, "family": "special", "price": 65, "magazine": 1, "reserve": 16, "damage": 24, "pellets": 1, "interval": 1.1, "reload": 2.6, "spread": 0.027, "sound": "crossbow", "ammo_type": "ARROW", "projectile_speed": 32, "noise_radius": 3.0, "range": 48, "effective_range": 21.6, "minimum_damage": 0.4, "recoil": 0.15, "kick": 0.008, "limb_force": 0.1, "ammo_cost": 1, "vital_bonus": 2.6, "reload_stages": ["TAKE AMMUNITION", "SET GRIP", "PREPARE", "READY"], "description": "Cheap, unforgiving and quiet. Curved flight; lead your target. Precise vital hits are essential."},
	{"id": "longbow", "name": "YEW LONGBOW", "tag": "23 / FIELDCRAFT", "year": 1700, "family": "special", "price": 115, "magazine": 1, "reserve": 16, "damage": 38, "pellets": 1, "interval": 1.1, "reload": 2.6, "spread": 0.015, "sound": "crossbow", "ammo_type": "ARROW", "projectile_speed": 45, "noise_radius": 3.0, "range": 70, "effective_range": 31.5, "minimum_damage": 0.4, "recoil": 0.15, "kick": 0.008, "limb_force": 0.1, "ammo_cost": 1, "vital_bonus": 2.2, "reload_stages": ["TAKE AMMUNITION", "SET GRIP", "PREPARE", "READY"], "description": "Cheap, unforgiving and quiet. Curved flight; lead your target. Precise vital hits are essential."},
	{"id": "recurve_bow", "name": "HORN RECURVE BOW", "tag": "24 / FIELDCRAFT", "year": 1700, "family": "special", "price": 160, "magazine": 1, "reserve": 16, "damage": 33, "pellets": 1, "interval": 1.1, "reload": 2.6, "spread": 0.008, "sound": "crossbow", "ammo_type": "ARROW", "projectile_speed": 51, "noise_radius": 3.0, "range": 85, "effective_range": 38.25, "minimum_damage": 0.4, "recoil": 0.15, "kick": 0.008, "limb_force": 0.1, "ammo_cost": 1, "vital_bonus": 2.2, "reload_stages": ["TAKE AMMUNITION", "SET GRIP", "PREPARE", "READY"], "description": "Cheap, unforgiving and quiet. Curved flight; lead your target. Precise vital hits are essential."},
	{"id":"iron_grenade","name":"IRON GRENADE","tag":"25 / ONE PER ROUND","year":1850,"family":"special","price":275,"magazine":1,"reserve":0,"damage":170.0,"pellets":1,"interval":1.2,"reload":1.0,"spread":.02,"sound":"crossbow","ammo_type":"ONE GRENADE","projectile_speed":13.0,"range":35.0,"explosive":true,"blast_radius":6.0,"fuse":2.8,"reload_stages":["EMPTY"],"description":"One carried grenade, restored free each round. Timed fuse; blast harms nearby hunters too."},
	{"id":"dynamite","name":"DYNAMITE BUNDLE","tag":"26 / ONE PER ROUND","year":1867,"family":"special","price":425,"magazine":1,"reserve":0,"damage":280.0,"pellets":1,"interval":1.2,"reload":1.0,"spread":.035,"sound":"crossbow","ammo_type":"ONE BUNDLE","projectile_speed":11.0,"range":30.0,"explosive":true,"blast_radius":9.0,"fuse":3.5,"reload_stages":["EMPTY"],"description":"One carried bundle, restored free each round. Longer fuse and a dangerous wide blast."},
	{"id":"aether_musket","name":"AETHER CRANK MUSKET","tag":"27 / EXPERIMENTAL FANTASY","year":1888,"family":"special","price":950,"magazine":5,"reserve":0,"damage":145.0,"pellets":1,"interval":.55,"reload":12.0,"spread":.002,"sound":"rifle","ammo_type":"AETHER CHARGE","laser":true,"range":180.0,"effective_range":140.0,"limb_force":2.5,"recoil":.25,"reload_stages":["UNLOCK DYNAMO","CRANK GENERATOR","CHARGE FIVE CELLS","LOCK & READY"],"description":"Fictional brass-and-walnut laser musket. Five beams; four seconds of cranking restores its charge."},
	{"id": "lancaster_four", "name": "LANCASTER FOUR-BARREL", "tag": "28 / FOUR-BARREL PISTOL", "year": 1882, "family": "sidearm", "price": 175, "magazine": 4, "reserve": 20, "damage": 49.0, "pellets": 1, "interval": 0.48, "reload": 7.5, "spread": 0.022, "sound": "pistol", "ammo_type": "PISTOL CARTRIDGE", "range": 85.0, "effective_range": 30.0, "recoil": 1.1, "kick": 0.035, "reload_stages": ["OPEN ACTION", "EXTRACT CASES", "LOAD CARTRIDGES", "CLOSE & READY"], "description": "Four fixed barrels, four quick shots. Affordable close-range insurance; tip open to reload."},
	{"id": "mauser_c78", "name": "MAUSER C78 ZIG-ZAG", "tag": "29 / 1878 REVOLVER", "year": 1878, "family": "sidearm", "price": 450, "magazine": 6, "reserve": 24, "damage": 57.0, "pellets": 1, "interval": 0.48, "reload": 9.0, "spread": 0.012, "sound": "revolver", "ammo_type": "PISTOL CARTRIDGE", "range": 85.0, "effective_range": 30.0, "recoil": 1.1, "kick": 0.035, "reload_stages": ["OPEN ACTION", "EXTRACT CASES", "LOAD CARTRIDGES", "CLOSE & READY"], "description": "A solid-frame Mauser revolver with distinctive zig-zag cylinder grooves. Six accurate cartridge shots."},
	{"id": "mauser_1871", "name": "MAUSER MODEL 1871", "tag": "30 / BOLT-ACTION RIFLE", "year": 1871, "family": "longarm", "price": 625, "magazine": 1, "reserve": 20, "damage": 165.0, "pellets": 1, "interval": 0.48, "reload": 5.4, "spread": 0.004, "sound": "heavy_rifle", "ammo_type": "RIFLE CARTRIDGE", "range": 160.0, "effective_range": 105.0, "recoil": 1.7, "kick": 0.052, "reload_stages": ["LIFT BOLT", "DRAW & EXTRACT", "LOAD CARTRIDGE", "LOCK BOLT"], "bullet_speed": 440.0, "description": "Long single-shot bolt-action rifle. Excellent reach and penetration; work the bolt between shots."},
	{"id": "gold_naval_pair", "name": "GOLD NAVAL PISTOLS", "tag": "31 / DUAL HEAVY PISTOLS", "year": 1840, "family": "sidearm", "price": 525, "magazine": 2, "reserve": 20, "damage": 155.0, "pellets": 1, "interval": 0.36, "reload": 12.0, "spread": 0.023, "sound": "musket", "ammo_type": "HEAVY PISTOL BALL", "range": 70.0, "effective_range": 28.0, "recoil": 1.85, "kick": 0.057, "reload_stages": ["HALF COCK BOTH", "POWDER & BALL", "RAM BOTH BARRELS", "CAP BOTH HAMMERS"], "dual": true, "description": "An ornate fictional pair of heavy naval percussion pistols. Right, then left; reload both to begin again."},
	{"year": 1780, "family": "sidearm", "pellets": 14, "interval": 0.26, "reload": 12.0, "spread": 0.085, "sound": "blunderbuss", "ammo_type": "LOOSE SHOT", "recoil": 2.0, "kick": 0.06, "range": 29.0, "effective_range": 9.0, "reload_stages": ["OPEN ACTION", "EXTRACT", "RELOAD", "READY"], "id": "dual_blunderbuss", "name": "TWIN BLUNDERBUSSES", "tag": "32 / DUAL SCATTERGUNS", "price": 475, "magazine": 2, "reserve": 16, "damage": 12.0, "minimum_damage": 0.18, "dual": true, "description": "Two short brass blunderbusses. Alternate hands; fourteen pellets each. Brutal up close, poor at range."},
	{"year": 1873, "family": "sidearm", "pellets": 1, "interval": 0.26, "reload": 16.5, "spread": 0.021, "sound": "revolver", "ammo_type": "PISTOL CARTRIDGE", "recoil": 1.1, "kick": 0.035, "range": 80.0, "effective_range": 30.0, "reload_stages": ["OPEN ACTION", "EXTRACT", "RELOAD", "READY"], "id": "dual_revolvers", "name": "PAIRED FRONTIER REVOLVERS", "tag": "33 / TWELVE SHOTS", "price": 800, "magazine": 12, "reserve": 36, "damage": 55.0, "dual": true, "description": "Two engraved six-shooters. Alternate hands through twelve shots, then reload both cylinders."},
	{"year": 1917, "family": "sidearm", "pellets": 1, "interval": 0.18, "reload": 8.4, "spread": 0.008, "sound": "revolver", "ammo_type": "PISTOL CARTRIDGE", "recoil": 0.7, "kick": 0.021, "range": 115.0, "effective_range": 60.0, "reload_stages": ["RELEASE DRUM", "FIT LOADED DRUM", "PULL TOGGLE", "READY"], "id": "luger_drum", "name": "ARTILLERY LUGER / DRUM", "tag": "34 / LATER-ERA PREMIUM", "price": 1000, "magazine": 32, "reserve": 64, "damage": 64.0, "description": "An explicit later-era exception: long-barrel Luger, toggle action and 32-round snail drum. Semi-automatic; premium price."},
	{"year": 1889, "family": "special", "pellets": 1, "interval": 0.9, "reload": 9.0, "spread": 0.02, "sound": "blunderbuss", "ammo_type": "EXPLOSIVE SHELL", "recoil": 1.1, "kick": 0.035, "range": 100.0, "effective_range": 65.0, "reload_stages": ["OPEN BREECH", "EXTRACT CASE", "LOAD SHELL", "LOCK BREECH"], "id": "grenade_mortar_1889", "name": "1889 EXPERIMENTAL HAND MORTAR", "tag": "35 / FICTIONAL PERIOD PROTOTYPE", "price": 900, "magazine": 1, "reserve": 8, "damage": 240.0, "projectile_speed": 32.0, "explosive": true, "launcher": true, "blast_radius": 7.0, "fuse": 4.0, "impact_fuse": true, "ammo_cost": 45, "description": "Fictional late-1800s hand mortar. One arcing explosive shell; impact fuse detonates on contact. Splash can hurt both hunters."},
	{"id":"fire_siphon","name":"PRIMITIVE FIRE SIPHON","tag":"36 / PRESSURISED FLAME","year":1880,"family":"special","price":850,"magazine":60,"reserve":120,"damage":7.0,"pellets":3,"interval":0.15,"reload":15.0,"spread":0.10,"sound":"flame","ammo_type":"FUEL PULSE","range":10.0,"effective_range":5.0,"minimum_damage":0.3,"flame":true,"automatic":true,"bullet_speed":80.0,"recoil":0.12,"kick":0.006,"noise_radius":35.0,"limb_force":0.0,"reload_stages":["SHUT VALVE","REPLACE FUEL","PUMP PRESSURE","RELIGHT PILOT"],"description":"Fictional hand-pumped brass fire siphon. Hold fire for a short, spreading flame jet. Walls stop the flame; nearby hunters can be burned."}
]
const LEMAT_SECONDARY := {"magazine":1, "reserve":4, "damage":10.0, "pellets":10, "reload":8.5, "interval":1.0, "spread":0.078, "sound":"blunderbuss", "ammo_type":"CENTRAL SHOT CHARGE", "recoil":1.75, "kick":0.055, "range":24.0, "effective_range":7.0, "minimum_damage":0.15, "ammo_cost":4, "reload_stages":["POUR POWDER","ADD SHOT","RAM WAD","PRIME CENTRAL BARREL"]}

static func weapon(index: int) -> Dictionary:
	var result: Dictionary = DEFAULTS.duplicate(true)
	result.merge(WEAPONS[clampi(index, 0, WEAPONS.size() - 1)], true)
	if is_gun(index): result.reload=float(result.reload)/3.0
	result.penetration = 1.15 if index in [14,15,26,29,30] else (.42 if str(result.family)=="sidearm" else .70)
	if int(result.pellets)>1: result.penetration=.28
	if index==18: result.penetration=.22
	if index==19: result.penetration=.30
	if index==20: result.penetration=.85
	if index in [21,22,23]: result.penetration=.40+(index-21)*.10
	if index==3: result.penetration=.65
	if index in [21,22,23]:
		result.spread *= .5
		result.aim_fov=62.0
		result.sight_zero=20.0
		result.description="Quiet hunting bow. Brass bead sighted at 20 metres. Aim higher beyond that and lead moving targets; precise vital hits reward patience."
	if result.get("flame",false): result.penetration = 0.01
	return result

static func secondary_weapon() -> Dictionary:
	var result := weapon(9)
	result.merge(LEMAT_SECONDARY, true)
	result.reload=float(LEMAT_SECONDARY.reload)/3.0
	result.penetration=.26
	return result

static func is_gun(index: int) -> bool:
	return (index>=0 and index<=17 and index!=3) or index>=26 and index<WEAPONS.size()

static func full_magazines() -> Array[int]:
	var result: Array[int] = []
	for entry in WEAPONS:
		result.append(int(entry.magazine))
	return result

static func full_reserves() -> Array[int]:
	var result: Array[int] = []
	for entry in WEAPONS:
		result.append(int(entry.reserve))
	return result
