"""Original 48 kHz gunshot effects; standard library only, deterministic rebuild.

Broadband muzzle crack, turbulent low/mid blast, a pressure impulse and filtered
outdoor reflections. No pitched oscillator or third-party recording is used.
"""
from pathlib import Path
import array
import json
import math
import random
import wave

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets/audio/gunshots"
RATE = 48000
# duration, crack decay, body decay, bass cutoff, bass weight, mid weight
PROFILES = {
    "musket": (2.15, 60, 7.5, 105, 5.4, 2.5),
    "shotgun": (1.65, 75, 10, 135, 4.8, 2.7),
    "rifle": (1.5, 110, 13, 155, 3.8, 2.2),
    "pistol": (1.25, 95, 12, 175, 3.4, 2.4),
    "revolver": (1.4, 100, 11, 145, 4.0, 2.3),
    "pepperbox": (1.05, 120, 15, 195, 3.0, 2.1),
    "blunderbuss": (2.35, 52, 6.5, 90, 6.0, 2.9),
    "heavy_rifle": (2.1, 85, 8.5, 115, 5.5, 2.8),
}


def render(kind, variant):
    duration, snap_decay, decay, cutoff, bass_gain, mid_gain = PROFILES[kind]
    rng = random.Random(1776 + list(PROFILES).index(kind) * 101 + variant * 31)
    n = int(duration * RATE)
    direct = array.array("d", [0.0]) * n
    low = mid = sub = 0.0
    bass_alpha = 1 - math.exp(-math.tau * cutoff / RATE)
    mid_alpha = 1 - math.exp(-math.tau * 1050 / RATE)
    sub_alpha = 1 - math.exp(-math.tau * 48 / RATE)
    for i in range(n):
        t = i / RATE
        noise = rng.uniform(-1, 1)
        low += bass_alpha * (noise - low)
        mid += mid_alpha * (noise - mid)
        sub += sub_alpha * (noise - sub)
        attack = min(1, t / .0004)
        crack = (noise - mid) * math.exp(-snap_decay * t) * .82
        blast = (mid - low) * mid_gain * math.exp(-decay * 1.6 * t)
        boom = (low - sub * .35) * bass_gain * math.exp(-decay * t)
        pressure = .65 * (math.exp(-80 * t) - math.exp(-650 * t))
        direct[i] = math.tanh((crack + blast + boom + pressure) * 1.65) * attack

    # Irregular diffuse returns from trees, rocks and the surrounding shoreline.
    filtered = array.array("d", [0.0]) * n
    reflection = 0.0
    for i, x in enumerate(direct):
        reflection += .10 * (x - reflection)
        filtered[i] = reflection
    mix = array.array("d", direct)
    for delay, gain in [(.043, .24), (.079, .18), (.131, .15), (.208, .12), (.327, .085), (.493, .045), (.701, .025)]:
        lag = int((delay + rng.uniform(-.006, .006)) * RATE)
        for i in range(lag, n):
            mix[i] += filtered[i - lag] * gain
    rumble = dc = 0.0
    for i in range(n):
        t = i / RATE
        rumble += .025 * (rng.uniform(-1, 1) - rumble)
        mix[i] += rumble * .85 * min(1, t / .04) * math.exp(-3.6 * t)
        # Remove DC and end on silence; echoes retain body without subsonic drift.
        dc += .0026 * (mix[i] - dc)
        mix[i] = (mix[i] - dc) * min(1, (duration - t) / .15)
    peak = max(abs(x) for x in mix)
    scale = 10 ** (-1.5 / 20) / peak
    pcm = array.array("h", (round(x * scale * 32767) for x in mix))
    assert max(abs(x) for x in pcm) < 32767
    path = OUT / f"{kind}_{variant + 1}.wav"
    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(RATE)
        wav.writeframes(pcm.tobytes())
    return pcm


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    reports = {}
    preview = array.array("h", [0]) * int(.35 * RATE)
    for kind in PROFILES:
        for variant in range(3):
            pcm = render(kind, variant)
            reports[f"{kind}_{variant + 1}"] = {
                "seconds": len(pcm) / RATE,
                "peak_dbfs": 20 * math.log10(max(abs(x) for x in pcm) / 32768),
                "rms_first_100ms_dbfs": 20 * math.log10(math.sqrt(sum((x / 32768) ** 2 for x in pcm[:4800]) / 4800)),
            }
            if variant == 0 and kind in ["musket", "revolver", "shotgun", "heavy_rifle"]:
                # Preview matches the local -6 dB playback gain.
                preview.extend(round(x * 10 ** (-6 / 20)) for x in pcm)
                preview.extend([0] * int(.5 * RATE))
    bank = ['extends RefCounted', '## Original effects generated by tools/build_gunshots.py.', 'const SAMPLES := {']
    for kind in PROFILES:
        files = ', '.join(f'preload("res://assets/audio/gunshots/{kind}_{i}.wav")' for i in range(1, 4))
        bank.append(f'\t"{kind}": [{files}],')
    bank.append('}\n')
    (ROOT / "scripts/gunshot_bank.gd").write_text('\n'.join(bank), encoding="utf-8")
    (ROOT / "qa/gunshot-levels.json").write_text(json.dumps(reports, indent=2), encoding="utf-8")
    with wave.open(str(ROOT / "qa/gunshot-preview.wav"), "wb") as wav:
        wav.setnchannels(1); wav.setsampwidth(2); wav.setframerate(RATE)
        wav.writeframes(preview.tobytes())
    print(f"Built {len(reports)} original gunshot samples and a four-gun preview.")


if __name__ == "__main__":
    main()
